# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

variables:
  imageRepository: 'app1nginx'
  containerRegistry: 'docker-service-connection'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

stages:
  - stage: Stage1
    displayName: Build and push image
    jobs:
      - job: Build
        displayName: Build and Push Image

        steps: 
        - task: Docker@2
          displayName: Build & Push image to ACR
          inputs:
            containerRegistry: '$(containerRegistry)'
            repository: '$(imageRepository)'
            command: 'buildAndPush'
            Dockerfile: '$(dockerfilePath)'
            tags: '$(Build.BuildId)'
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'azure-vs-sub-connection'
            addSpnToEnvironment: true
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: 'az account show'
