# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

variables:
  imageRepository: 'app1nginx'
  containerRegistry: 'docker-service-connection'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

stages:
  - stage: Stage1
    displayName: Build and push image
    jobs:
      - job: Build
        displayName: Build and Push Image

        steps: 
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              az login -u m.waseem.ebrahim@accenture.com -p $(MY_PASSWORD)
              az account show
